name: Run Selenium Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:  
  selenium-tests:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v3  

      - name: Set Up Java  
        uses: actions/setup-java@v3  
        with:  
          java-version: '11'
          distribution: 'temurin'	

      - name: Upload Cucumber Report
        if: always() # Ensures this step runs even if tests fail
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: target/cucumber-report.html

      - name: Install Dependencies  
        run: mvn install  

      - name: Run Tests  
        run: mvn test
